name: Build Linux wheels only

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:          

jobs:
  build_linux_wheels:
    name: Build manylinux wheels
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19
        env:
          
          CIBW_BUILD: cp3{8,9,10,11,12}-manylinux_x86_64
          CIBW_BEFORE_ALL: |
            curl -L https://github.com/oneapi-src/oneTBB/releases/download/v2021.12.0/oneapi-tbb-2021.12.0-lin.tgz | tar -xz -C /opt
            echo "/opt/oneapi-tbb-2021.12.0/lib/intel64/gcc4.8" >/etc/ld.so.conf.d/tbb.conf && ldconfig
            dnf install -y libpng-devel zlib-devel libjpeg-devel libtiff-devel
            export CMAKE_PREFIX_PATH=/opt/oneapi-tbb-2021.12.0:$CMAKE_PREFIX_PATH
          CIBW_SKIP: "*-musllinux*"
          
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-wheels
          path: ./wheelhouse/*.whl